export const TooltipText = {
  AddFile: '新建文件',
  RenameFile: '重命名',
  DeleteFile: '删除',
  isEntry: '入口文件',
  SetEntry: '设为入口文件',
  ToggleFiles: (show: boolean) => `${show ? '隐藏' : '显示'}文件栏`,
  ToggleCode: (show: boolean) => `${show ? '隐藏' : '显示'}代码编辑器`,
  Settings: '设置',
  ToggleConsole: (show: boolean) => `${show ? '关闭' : '打开'}控制台`,
  ToggleWebPreview: (show: boolean) => `${show ? '隐藏' : '显示'}预览区`,
  RefreshWebPreview: '刷新预览',
  SwapLayout: '交换代码编辑器和预览区的位置',
  CopyCode: '复制代码到剪贴板',
  FormatCode: '格式化代码',
  Share: '分享页面',
  Docs: '查看 Code 文档',
  Github: '在 GitHub 上查看 Code',
};
